# helm install jellyfin k8s-at-home/jellyfin -f jellyfin.yaml
#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#

# -- environment variables. See [image docs](https://jellyfin.org/docs/general/administration/configuration.html) for more details.
# @default -- See below
env:
  # -- Set the container timezone
  TZ: "Europe/Amsterdam"

image:
  # -- image repository
  repository: "{{ site_image }}"
  # -- image tag
  # @default -- chart.appVersion
  tag: latest
  # -- image pull policy
  pullPolicy: Always

# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    ports:
      http:
        port: 80

ingress:
  main:
    ingressClassName: traefik
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.tls: "true"
    enabled: true
    hosts:
      - host: "{{ domain_name }}"
        paths:
          - path: /
            pathType: Prefix
    tls:
      - hosts:
        - "{{ domain_name }}"
        secretName: wildcard-cert
