---
- ansible.builtin.import_tasks: prepare.yml
  tags: never, prepare
- ansible.builtin.import_tasks: ssl.yml
  tags: ssl
- ansible.builtin.import_tasks: storage.yml
  tags: storage
- ansible.builtin.import_tasks: ingress.yml
  tags: ingress
- ansible.builtin.import_tasks: charts.yml
  tags: charts