apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-db-pv
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 15Gi
  nfs:
    path: "{{ nfs_storage_path }}/named-wordpress-mysql-data"
    server: "{{ truenas_ip }}"
  storageClassName: nfs-client
  claimRef:
    namespace: default
    name: wordpress-db-pvc