apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    # The ACME server URL
    server: "{{ letsencrypt_directory }}"
    # Email address used for ACME registration
    email: "{{ cloudflare_email }}"
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt
    # Enable the DNS-01 challenge provider
    solvers:
    - dns01:
        cloudflare:
          email: "{{ cloudflare_email }}"
          apiTokenSecretRef:
            name: cloudflare-api-token-secret
            key: api-token
